config/routes.rb
Rails.application.routes.draw do
  get 'works' => 'support#how_it_works'

  get "faqs" => 'support#faq'

  get 'support/contact'

  get 'groups' => 'pages#groups'
  
  get 'moreworks' => 'support#moreworks'

  root 'pages#about_us'

  get 'kids' =>'pages#kidscare'

  get 'values' => 'pages#our_values'

  get 'privacy' =>'pages#privacy_policy'

  get 'terms' => 'pages#terms_and_conditions'

  get 'media' => 'pages#news_and_media'
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def about_us
  end

  def kidscare
  end

  def groups
  end

  def our_values
  end

  def privacy_policy
  end

  def terms_and_conditions
  end

  def news_and_media
  end
end

app/controllers/support_controller.rb
class SupportController < ApplicationController
  def how_it_works
  end

  def moreworks
  end

  def faq
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/support_helper.rb
module SupportHelper
end

app/views/layouts/_footer.html.erb
<div id="footer-link">
	<div id="footer-main">
    	<div class="kids-care">
        	<div class="kids-care-in">
            	<h1>Kids Care Help</h1>
                <div class="f-link"><a href="/kids">About Us</a></div>
                <div class="f-link"><a href="/values">Our Values</a></div>
                <div class="f-link"><a href="/privacy">Privacy Policy</a></div>
                <div class="f-link"><a href="/terms"> Terms &amp; Conditions</a></div>
                <div class="f-link"><a href="/media">News &amp; Media</a></div>
            </div>
        </div>
        <div class="kids-care">
        	<div class="kids-care-in">
            	<h1>Support</h1>
                <div class="f-link"><a href="/works">How it works</a></div>
                <div class="f-link"><a href="/faqs">FAQ</a></div>
                 <div class="mail-info"><a href="mailto:customersupport@kidscarehelp.com.au">customersupport@kidscarehelp.com.au</a></div>
                <h2>Contact Us</h2>
                <div class="mail-info"><a href="mailto:info@kidscarehelp.com.au">info@kidscarehelp.com.au</a></div>
            </div>
        </div>
        <div class="social">
        	<div class="kids-care-in">
            	<h1>Social Media</h1>
                <div class="icon-f"><a href="https://www.facebook.com/pages/kidscarehelpcomau/251792708354806?ref=hl" target="_blank">Like us on Facebook</a></div>
                <div class="icon-t"><a href="https://twitter.com/KidsCare_Help" target="_blank">Follow us on Twitter</a></div>
                <div class="icon-g"><a href="https://plus.google.com/u/0/b/104191544741347745020/104191544741347745020/about" target="_blank">Connect us on google+</a></div>
                
            </div>
        </div>  
        <div style="clear:both;"></div> 
    </div>    
</div>
<div id="footer">
    <div id="footer-bg-left">
        <div id="footer-bg-right">
            <div id="footer-mid">
            <div class="bottom-logo"></div>
            <div class="copy">© 2014 <span class="footer-mid-blue">kidscarehelp.com.au</span> . ABN  58387692783.</div>
            </div>
        </div>
    </div>
</div>

app/views/layouts/_form.html.erb
<div id="form">
    <div id="form-in">
    	<div class="tittext">Sign Up Now for a 90 Day Free Trial</div>
		                    	<div class="hspace">&nbsp;</div>
                        
        <form action="#" method="post">
            <div></div>
            <div><input name="NAME" type="text" placeholder="Name" class="form-feild1" required="required"></div>
            <div><input name="EMAIL" type="email" placeholder="Email Address" class="form-feild2" required="required"></div>
            <div><input name="PASSWORD" type="Password" placeholder="Choose a Password" class="form-feild3" required="required"></div>
            <div><input type="checkbox" required="required"> I agree to the <a href="terms_and_conditions.php" target="_blank">Terms and Conditions</a> of Kids Care Help</div>
            <div style="height:5px;"></div>
            <input type="hidden" value="0" name="signpage">
            <div><input class="fsSubmitButton" type="submit" name="submit" value="Get Started"></div>
        </form>
    </div>
</div>

app/views/layouts/_navigation.html.erb
<nav class="navbar navbar-default navbar-custom">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to root_path do %>
        <%= image_tag('logo.png', class:"navbar-brand logo") %>
      <% end %>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        <li class="work"><%=link_to "Find Groups", '/groups' %></li>
        <li class ="work"><%=link_to "How It Works", works_path %></li>
        <li id="faq" class="work"><%=link_to "FAQ", faqs_path %></li>
        <li id='login'>
          <%=link_to '#' do   %>
            <%=image_tag 'l-graphics.png' %>  Login
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Kidscare</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => false %>
  <link rel='shortcut icon' type='image/x-icon' href='images/favicon.ico' />
  <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.6.1/css/font-awesome.min.css" rel="stylesheet" integrity="sha384-hQpvDQiCJaD2H465dQfA717v7lu5qHWtDbWNPvaTJ0ID5xnPUlVXnKzq7b8YUkbN" crossorigin="anonymous">
<link href='https://fonts.googleapis.com/css?family=Roboto:400,700,500,900,100|Open+Sans:400,700,800,300' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<%= render 'layouts/navigation' %>
<div>
	<%= yield %>
</div>
<%= render 'layouts/footer' %>
</body>
</html>

app/views/pages/about_us.html.erb
<div id="mid">
    <div id="mid-main">
    	<h1>DO YOU NEED OCCASIONAL CARE?</h1>
    	<h2>Kids Care Help: Babysitting Help from People you Trust</h2>
    	<h3>On Kids Care Help you create or join a Mothers Babysitting Group. Being part of a group of trusted mothers makes it easy to find a babysitter when you most need it.</h3>
        <div id="main-video">
            <div id="video-left">
                <h1>LEARN MORE ABOUT</h1>
                <h3>MOTHERS BABYSITTING GROUP</h3>
                <div class="arrow-video"><%= image_tag('arrow-video.png') %></div>
                    <div class="sign"><a href="sign-up.php">Sign Up Now</a></div>
                    <p class="sitting-box-t" style="color:#000;">90 Day Free Trial</p>
                                        </div>
        	<div id="video-right">
                <iframe class="video-v" src="//www.youtube.com/embed/8YeBVpkH7mg?enablejsapi=1&amp;feature=player_detailpage" frameborder="0" allowfullscreen=""></iframe>
            </div>
                <div class="sign1"><a href="sign-up.php">Sign Up Now</a></div>
        </div>
    </div>
</div>
<div class="icon"><%= image_tag('i-01.png', width:"66", height: "60" ) %>
<div class="container">
    <div id="sitting">
        <h1>WHY MOTHERS BABYSITTING GROUP?</h1>
        <div id="set-box">
            <div class="sitting-box">
                <p><%= image_tag('icon-build.png', width:"102", height: "102" ) %></p>
                <p class="sitting-box-t">Babysitting help from a community of mothers you know and trust</p>
            </div>
            <div class="sitting-box">
                <p><%= image_tag('icon-cordinate.png', width:"102", height: "102" ) %></p>
                <p class="sitting-box-t">Arrange a babysitter simply and easily online</p>
            </div>
            <div class="sitting-box">
                <p><%= image_tag('icon-commition.png', width:"102", height: "102" ) %></p>
                <p class="sitting-box-t">Save on babysitting costs. Pay a subscription fee of $6.50/month</p>
            </div>
            <div class="sitting-box">
                <p><%= image_tag('icon-power.png', width:"102", height: "102" ) %></p>
                <p class="sitting-box-t">Use your community to help and support each other on parenting topics/issues</p>
            </div>
        </div>
        <div style="clear:both;"></div>   
    </div>
</div>
<div class="icon-b"><%= image_tag('i-02.png') %></div>
<div id="sign">
    <h1>ONCE YOU SIGN UP, YOU CAN</h1>
    <div class="sign-in">
        <div class="sign-in-left"><%= image_tag("icon-create.png", alt: "") %></div>
        <div class="sign-in-right">Create your own Mothers Babysitting Group or join an existing Group</div>
        <div style="clear:both;"></div>
    </div>
    
    <div class="sign-in">
        <div class="sign-in-left"><%= image_tag("icon-book.png", alt: "") %></div>
        <div class="sign-in-right">Book &amp; manage babysitting help with your group members with a simple and easy to coordinate online system</div>
        <div style="clear:both;"></div>
    </div>
    
    <div class="sign-in">
        <div class="sign-in-left"><%= image_tag("icon-organise.png", alt: "") %></div>
        <div class="sign-in-right">Organise mothers catch ups, playdates and events with your group</div>
        <div style="clear:both;"></div>
    </div>
    
    <div class="sign-in">
        <div class="sign-in-left"><%= image_tag("icon-share.png", alt: "") %></div>
        <div class="sign-in-right">Share your experiences with the group with Photos and Posts</div>
        <div style="clear:both;"></div>
    </div>
    
    <div class="sign-in">
        <div class="sign-in-left"><%= image_tag("icon-member.png", alt: "") %></div>
        <div class="sign-in-right">See how each member is helping the group through a "Pay it Forward" Babysitting Board</div>
        <div style="clear:both;"></div>
    </div>
</div>
<div class="icon-b"><%= image_tag('i-03.png', alt:"") %></div>
<%= render 'layouts/form' %>

app/views/pages/kidscare.html.erb
<div id="inner">
	<h1>About Us</h1>
    <p>Arranging a babysitter is never an easy task, especially finding someone that you trust.</p>
    <p>Regardless of whether you are still in the workforce or a stay at home mum, there will always be times when you need a babysitter urgently. We can help you when you need to attend an appointment, have work commitments, an urgent issue to attend to or just need to have a night out with your girlfriends.</p>
    <p>The inspiration for Kids Care Help came from listening to the challenges that parents encounter in finding babysitting help.</p> <p>&nbsp;</p>
    <p>We identified the most important criteria that parents ascribe to finding a babysitter:</p>
    <p>
        * It is provided by a person that parents trust<br>
        * They have easy access to people who can help<br>
        * It is Affordable<br>
        * The process of finding a babysitter is simple and easy to coordinate/manage
    </p><p>&nbsp;</p>
        
    <p>Kids Care Help believes that recent technological advances mean that parents can now find trusted babysitters online. We achieve this by setting up a community where parents can share information with one another to build a circle of trust that helps them make informed decisions on babysitters.</p>
    <p>We launched our first service offering targeted towards Mothers by giving them the ability to form a Mothers Babysitting Group. With a Mothers Babysitting Group, mothers can join or create groups and seek one another’s assistance to get babysitting help.</p>
    <p>We plan to launch more services as the business grows, so stay tuned. </p>
    <p>&nbsp;</p>
    
    <p><strong>Our Vision</strong></p>
    <p>To build an online platform that makes it easy for parents to find childcare by offering a choice of services that suits their needs.</p>
    <p>&nbsp;</p>
    
    <h1>Founder</h1>
    <p><strong>Anirudh (Ani) Nair</strong> - Founder , Kids Care Help</p>
    <p>Kids Care Help is the brainchild of Ani Nair. Ani was motivated by the challenge of helping families find childcare in a simple and cost effective way.</p>
    <p>With experience in strategy formulation and as a management consultant in large and medium sized corporations, Ani brings his problem solving and thought leadership capabilities to Kids Care Help.</p>
    <p>He is responsible for the formulation and implementation of the Strategy for Kids Care Help. He also manages Business Development and the day-to-day operations for Kids Care Help.</p>
    <p>Ani holds a degree in Executive MBA from the Australian Graduate School of Management (AGSM) and a Bachelors/Masters degree in Computer Science.</p>       
    <p>Outside of work, Ani loves to travel and experience different cultures and to be inspired by TED Talks. Further details of Ani’s professional career can be viewed on LinkedIn.</p>
    <p><span class="group-box-text"><a href="https://www.linkedin.com/in/aninair" target="_blank">https://www.linkedin.com/in/aninair</a></span></p>
</div>
<!--Inner page end-->
<div class="clearfix"></div>

app/views/pages/news_and_media.html.erb
<div id="inner">
	<h1>New and Media</h1>
    <p><%= image_tag('news.jpg', alt:"kids care news") %></p>
	<h2>For All Media enquiries , please contact</h2>
	<p><strong>Ani Nair</strong><br>
  	Founder Kids Care Help<br>
  	Email - <span class="group-box-text"><a href="mailto:ani.nair@kidscarehelp.com.au">ani.nair@kidscarehelp.com.au</a></span></p>
</div>

app/views/pages/our_values.html.erb
<div class=" container-fluid">
    <h6 class="value-t-green-title">OUR VALUES DEFINE HOW WE THINK AND BEHAVE</h6>
    <div class="col-md-4">
        <div class="media">
            <a class="media-left media-middle" href="#"><%= image_tag('v1.jpg', alt:"")%></a>
            <div class="media-body">
                <div class="value-text"> 
                    <span class="value-t-blue" style="color:#000; text-transform:none">We serve mothers/parents not customers </span> <br>
                    Understanding their needs drives everything we do
                </div>
            </div>
        </div>
        <div style="height:20px;"></div>
    </div>
    
    <div class="col-md-4">
        <div class="media">
            <a class="media-left media-middle" href="#"><%= image_tag('v2.jpg', alt:"")%></a>
            <div class="media-body">
                <div class="value-text"> 
                    <span class="value-t-orange" style="color:#000; text-transform:none">Building trust is central to every solution </span> <br>
                    Every solution should help mothers make trusted decisions about babysitters<br><br>
                </div>
            </div>
        </div>
    </div>
    
    <div class="col-md-4">
        <div class="media">
            <a class="media-left media-middle" href="#"><%= image_tag('v3.jpg', alt:"")%></a>
            <div class="media-body">
                <div class="value-text"> 
                    <span class="value-t-purple" style="color:#000; text-transform:none">We work together with a community spirit</span> <br>
                    Everyone shares in the values, goals and objectives based on what we aim to achieve
                </div>
            </div>
        </div>
        <div style="height:20px;"></div>
    </div>
</div>
<div style="height: 40px"></div>
<div class=" container-fluid">
        <div class="col-md-4">
            <div class="media">
                <a class="media-left media-middle" href="#"><%= image_tag('v4.jpg', alt:"")%></a>
                <div class="media-body">
                    <div class="value-text"> 
                        <span class="value-t-purple" style="color:#000; text-transform:none">Humility</span> <br>
                        is a quality we all need to have. It is non-negotiable
                    </div>
                </div>
            </div>
            <div style="height:20px;"></div>
        </div>
        
        <div class="col-md-4">
            <div class="media">
                <a class="media-left media-middle" href="#"><%= image_tag('v5.jpg', alt:"")%></a>
                <div class="media-body">
                    <div class="value-text"> 
                        <span class="value-t-green" style="color:#000; text-transform:none">Drive change</span> <br>
                        "Most importantly, be the change you want to see"
                    </div>
                </div>
            </div>
            <div style="height:20px;"></div>
        </div>
        
        <div class="col-md-4">
            <div class="media">
                <a class="media-left media-middle" href="#"><%= image_tag('v6.jpg', alt:"")%></a>
                <div class="media-body">
                    <div class="value-text"> 
                        <span class="value-t-red" style="color:#000; text-transform:none">Be ambitious, open, honest and communicate to build trust with others </span> <br>
                         Doing so helps you enjoy work
                    </div>
                </div>
            </div>
            <div style="height:20px;"></div>
        </div>

    </div>

app/views/pages/privacy_policy.html.erb
<div id="inner">
    	<h1>About this Policy</h1> 
		<p><strong>What to read first</strong></p> 
		<p>The best place to start is by reading our simplified privacy policy which can be found here. It is a great way to get an understanding of how we collect, use and disclose your personal information. The extended privacy policy will give you a more comprehensive explanation of how your data is handled by Kids Care Help. If there's anything that is not clear from this privacy policy, please feel free to email us at <span class="group-box-text"><a href="mailto:info@kidscarehelp.com.au">info@kidscarehelp.com.au</a></span><br></p> <p></p>
		<p><strong>Our Principles</strong></p> 
		<p>We have a simple approach to data protection and privacy which adheres to the <span class="group-box-text"><a href="http://www.oaic.gov.au/images/documents/privacy/privacy-resources/privacy-fact-sheets/privacy-fact-sheet-17-australian-privacy-principles_2.pdf" target="_blank">13 Australian Privacy Principles</a></span></p> 
		<p>Our obligations under the Privacy Act 1988 (Privacy Act):</p>

		<p>This privacy policy sets out how we comply with our obligations under the Privacy Act. As an Australian based organisation, we are bound by the <span class="group-box-text"><a href="http://www.comlaw.gov.au/Details/C2012A00197" target="_blank">Australian Privacy Principles</a></span> (APPs) in the Privacy Act which regulate how organisations may collect, use, disclose and store personal information, and how individuals may access and correct personal information held about them. 
		In this privacy policy, 'personal information' has the same meaning as defined by <span class="group-box-text"><a href="http://www.comlaw.gov.au/Details/C2012C00903/Html/Text#_Toc343249829" target="_blank">section 6 of the Privacy Act</a></span>: information or an opinion (including information or an opinion forming part of a database), whether true or not, and whether recorded in a material form or not, about an individual whose identity is apparent, or can reasonably be ascertained, from the information or opinion.<br>
		</p><p></p>
		<h1>Collection</h1> 
		<p>We collect your personal information so that we can provide you with the products, services or information that we supply. Sometimes we collect personal information from a third party or from a publicly available source, but only if you have consented to your information being used in this way, or would reasonably expect us to collect it in this way. We only collect this information from companies or sources that are allowed to disclose it to us. Below you will find a breakdown of the different ways your personal information is collected.</p> <br><p></p>
		<p><strong>What we collect from you</strong></p> 
		<p><strong>User contact forms</strong></p> 
		<p>When you fill out a contact form wishing to get in touch with us, we will collect that information and use it to get in touch with you in response to your query. We may use the information to reach out to you to inform you of some of the services we provide, provided it is in line with your original query.</p><p></p>	
		<p><strong>When you sign up with us and create a login with us</strong></p> 
		<p>When you sign up to our website using your personal details, we will collect this personal information so that your user preferences are stored when you come back and login.</p><p></p>	
		<p><strong>Credit card payments including PayPal</strong></p> 
		<p>If you make a credit card payment on our website please be aware that in some instances your credit card details may be made fully available to us so that we can process your payment. You can rest assured in that we destroy all credit card information the moment the payment has gone through.</p><p>If you pay on our website through a payment service such as PayPal, then we will only receive basic information and confirmation of payment. We will not have any access to your credit card details as these are handled by PayPal or another 3rd party payment provider inline with their terms of use.</p>	<p></p>
		<p><strong>Age eligibility 18+</strong></p> 
		<p>The contents and or services provided by our website are intended for persons over the age of 18. By agreeing to our terms or request for age verification, you are stating that you are over the age of 18 and understand that we may collect that information to allow access to the website.</p>	
		<p><strong>Contacting Support</strong></p> 
		<p>If you contact us for any technical, product or other website related support, we may retain that information on record so as to process your request as well as for training purposes. Such information may include the transcript, emails or other information which was relayed by you and Kids Care Help throughout the support request process.</p><p></p>	
		<p><strong>What we collect from your online activity</strong></p> 
		<p>www.kidscarehelp.com.au uses cookies and other digital identifiers that fall into the following 3 types:</p>
		<p>Site performance indicators: these give us information on how our websites are used, so that we can make the necessary improvements or amendments to make your experience a better one.</p><p>Analytics Cookies: these give us the statistics to understand how many people are on our website, which areas are popular and which areas we need to work on.</p>

		<p>Advertising Cookies: we use these cookies to understand what type of advertising would be better suited to someone like you. That way, you would receive ads that are more likely to be relevant to you.</p>
		<p>Cookie rights: You can always disable the use of cookies by changing the security settings of your browser. Just bear in mind that this may affect how some items are displayed on our website.</p><p></p>	
		<p><strong>What we collect and receive from others</strong></p> 
		<p>We may also collect personal information from other companies that are able to disclose it to us as this information is received in line with their privacy policies.</p><p></p> 
		<p><strong>Sign in with Facebook</strong></p>
		<p>If you use Facebook to sign up to www.kidscarehelp.com.au, your Kids Care Help account will be connected automatically to your Facebook account, and information regarding your activity on www.kidscarehelp.com.au may be shared with Facebook, may be published in your timeline and may be on your Facebook friends' news feeds.If you would like more information it would be best to go directly to the Facebook privacy policy (which can be found <span class="group-box-text"><a href="https://www.facebook.com/about/privacy/" target="_blank">here</a> </span>or on their website), since this information is collected by Facebook and provided to us under the terms of their privacy policy.</p>	<p></p>
		<p> 
		<strong>Social Network widgets and buttons (Pinterest, Twitter etc)</strong> 
		</p>
		<p>By clicking or using any social network widgets on our website, you understand that you do so according to the terms and privacy policy of those services. 'Liking' or 'Following', and content using these widgets, may become visible to your social network.</p><p></p>	
		<p> 
		<strong>Maps/Video and other embedded content</strong> 
		</p> 
		<p>Embedded content such as Google Maps, YouTube videos etc is embedded or placed on our website - it is not hosted on our servers and therefore any interaction with such services is done so according to their privacy policy.</p><p></p>
		<p> 
		<strong>3rd party commenting (Disqus, Livefyre, IntenseDebate, Google+ etc)</strong> 
		</p> 
		<p>Where your personal information is contained in a user generated post or in a communication through a third party commenting system, please be aware that the comment made may become, and remain public.</p>	
		 
		<h1>Use and Disclosure</h1> 
		<p>We only use personal information for the purpose which was requested of us, or for the purposes which directly relate to one of our functions or activities. We will not provide your personal information to other entities or bodies, or any other party unless one of the following applies (as per and in line with APP 6 - use and disclosure of personal information):</p> 
		<p>
		* You have consented. 
		</p><p>* You would reasonably expect, or have been informed, that information of such kind would be passed on to those individuals, entities or bodies (for more information, see subclause 6.2).
		  </p> 
		<p>* It is otherwise required or authorised by law, or reasonably necessary for the enforcement of a criminal law or of a law imposing a pecuniary penalty, or for the protection of public revenue.</p> 
		<p>* It may prevent or lessen a serious and imminent threat to somebody's life or health.</p> 
		<p></p>
		<h1>Direct Marketing</h1> 
		<p>When it comes to direct marketing, no one likes being spammed. At Kids Care Help, we may use your personal information to send you advertising that is customised to your interests, characteristics or general location.</p><p><strong>Opt-out:</strong> As with all direct marketing correspondence that you receive from us via email, there is always an unsubscribe button or link located at the bottom of the email. With this you can manage which messages you receive from us.</p>	
		<h1>Quality of Personal Information</h1> 
		<p>We do what we can to keep your personal information up to date and accurate at all times as this allows us to deliver a better service to you. If any information we have for you needs to be corrected, you can contact us via<span class="group-box-text"> <a href="mailto:info@kidscarehelp.com.au">info@kidscarehelp.com.au</a></span></p> 
		<h1>Data Security</h1> 
		<p>We take active steps to protect the personal information we hold against loss, unauthorised access, use, modification or disclosure, and against other misuse. These steps include password protection for all of our IT systems. While we cannot share with you details of our entire security system for safety reasons, if you have any questions, you can always contact us at <span class="group-box-text"><a href="mailto:info@kidscarehelp.com.au">info@kidscarehelp.com.au</a></span></p> 
		<p>When no longer required or requested by you, all personal information is destroyed in a secure manner.</p> 
		<h1>Cross-border Disclosure of Personal Information</h1> 
		<p>Some of your personal information may be stored with or disclosed to other entities overseas (who are not in Australia or an external Territory) who are direct partners that assist us in providing our service. As per <span class="group-box-text"><a href="http://www.comlaw.gov.au/Details/C2012A00197" target="_blank">APP 8</a></span>, we have taken steps to ensure that the overseas recipient does not breach the Australian Privacy Principles. We also have in place policies and procedures to safeguard the handling of your personal data by such entities.</p> <h1>Access and Correction</h1> 
		<p>At Kids Care Help, we do everything we can to keep your personal information accurate. If you find that any information we hold about you is incorrect, you can contact us at <span class="group-box-text"><a href="mailto:info@kidscarehelp.com.au">info@kidscarehelp.com.au</a></span>, or as per the contact details below and we will endeavour to assist you with your questions. Please bear in mind that under Australian privacy laws, there may be situations where we cannot provide access to such personal information. For instance, if it would reasonably affect someone else's privacy or may pose a threat to someone's life, health or safety. </p> 
		<p>For any personal information that is collected by third parties, even when you are visiting our website, it is best to view their privacy policy and seek assistance from those parties directly.</p> 
		<h1>Complaints Handling</h1> 
		<p>If you have any complaints or feel that there has been a breach of the Australian Privacy Principles, or a registered APP code, you can contact us at <span class="group-box-text"><a href="mailto:info@kidscarehelp.com.au">info@kidscarehelp.com.au</a></span> or via another option below.</p> 
		<p>If you are not satisfied with the process of making a complaint to our Privacy Officer you may make a complaint to the Information Commissioner on the details below:<br>Office of the Australian Information Commissioner<br>GPO Box 5218 Sydney NSW 2001 <br>Email: <span class="group-box-text"><a href="mailto:enquiries@oaic.gov.au">enquiries@oaic.gov.au</a></span> <br>Telephone: 1300 363 992 <br>Fax: 02 9284 9666</p> 
		<h1>How to Contact Us</h1> 
		<p>We understand that your personal information is important to you and are thrilled that you made it this far! If you have any questions or concerns about this policy or our practices you can get in touch with us in the following ways:<br><br>Email: <span class="group-box-text"><a href="mailto:info@kidscarehelp.com.au">info@kidscarehelp.com.au</a></span><br>Address: Kids Care Help, Epping Road, Lane Cove, Sydney, NSW, 2066</p> 
		<p>This privacy policy was created on 19/07/2014 by <span class="group-box-text"><a href="http://www.myprivacypolicy.com.au" target="_blank">My Privacy Policy</a></span>.</p> 
        
  </div>

app/views/support/contact.html.erb
<h1>Support#contact</h1>
<p>Find me in app/views/support/contact.html.erb</p>